export const products = [
  {
    id: '1',
    slug: 'turquoise-desert-necklace',
    name: 'Turquoise Desert Necklace',
    price: 85,
    category: 'Necklaces',
    categorySlug: 'necklaces',
    tagline: 'Sky & stone, hand-strung',
    description:
      'Each bead in this necklace was hand-selected from natural turquoise stones found in the American Southwest. I string every piece myself, knotting between each bead so the necklace moves like water. The sterling silver toggle clasp is handmade by a silversmith I met at a craft market in Santa Fe. No two pieces are exactly alike — the variation in the turquoise is what makes it alive.',
    materials: 'Natural turquoise, seed beads, sterling silver toggle clasp',
    dimensions: '18" length, pendant 1.5"',
    colors: ['turquoise', 'silver'],
    placeholderClass: 'placeholder-turquoise',
    inStock: true,
    featured: true,
    isNew: true,
  },
  {
    id: '2',
    slug: 'sunrise-beaded-bracelet',
    name: 'Sunrise Beaded Bracelet',
    price: 45,
    category: 'Bracelets',
    categorySlug: 'bracelets',
    tagline: 'Warm as the first light',
    description:
      'I beaded this bracelet thinking about desert mornings — the way the sky moves from deep violet to peach to gold in less than an hour. Seed beads in coral, amber, and cream are woven on a flexible wire foundation so it drapes naturally on your wrist. It stretches slightly to fit most wrists without a clasp.',
    materials: 'Glass seed beads (size 11/0), beading wire, sterling crimps',
    dimensions: '7.5" circumference, ¾" wide',
    colors: ['coral', 'amber', 'cream'],
    placeholderClass: 'placeholder-sunrise',
    inStock: true,
    featured: true,
    isNew: false,
  },
  {
    id: '3',
    slug: 'mesa-hoop-earrings',
    name: 'Mesa Hoop Earrings',
    price: 65,
    category: 'Earrings',
    categorySlug: 'earrings',
    tagline: 'Layered like canyon walls',
    description:
      'Inspired by the layered red-and-tan bands of sandstone mesas, these hoops are wrapped with tiny seed beads in terracotta, sand, and cream. The wrapping is tight and even — I use a technique my grandmother taught me, pulling each bead flush to the last. Sterling silver ear wires are hypoallergenic and nickel-free.',
    materials: 'Glass seed beads, 14k gold-filled hoops, sterling silver ear wires',
    dimensions: '1.25" diameter hoops',
    colors: ['terracotta', 'sand', 'cream'],
    placeholderClass: 'placeholder-mesa',
    inStock: true,
    featured: false,
    isNew: true,
  },
  {
    id: '4',
    slug: 'prairie-flower-ring',
    name: 'Prairie Flower Ring',
    price: 38,
    category: 'Rings',
    categorySlug: 'rings',
    tagline: 'A wildflower for your finger',
    description:
      'A tiny beaded flower sits atop a simple adjustable band. The petals are pale pink seed beads, the center a cluster of yellow gold-toned beads. I make these one at a time and the petal count varies slightly — some have five petals, some six. The band adjusts to fit sizes 5–9.',
    materials: 'Glass seed beads, brass adjustable ring band',
    dimensions: 'Adjustable, fits sizes 5–9',
    colors: ['blush', 'sage', 'gold'],
    placeholderClass: 'placeholder-prairie',
    inStock: true,
    featured: false,
    isNew: false,
  },
  {
    id: '5',
    slug: 'canyon-sunset-necklace',
    name: 'Canyon Sunset Necklace',
    price: 120,
    category: 'Necklaces',
    categorySlug: 'necklaces',
    tagline: 'Every bead a moment in time',
    description:
      'This is one of my longer, more elaborate pieces — a statement necklace that took me nearly three weeks to complete. The gradient moves from deep burgundy at the clasp through coral, amber, and finally gold at the center pendant. The pendant is a hand-carved bone bead I sourced from a craftsperson in New Mexico. I love how the whole piece feels like watching a sunset in one glance.',
    materials: 'Glass seed beads, hand-carved bone pendant, brass clasp',
    dimensions: '22" length, pendant 2"',
    colors: ['burgundy', 'coral', 'amber', 'gold'],
    placeholderClass: 'placeholder-canyon',
    inStock: true,
    featured: true,
    isNew: false,
  },
  {
    id: '6',
    slug: 'woven-earth-cuff',
    name: 'Woven Earth Cuff',
    price: 72,
    category: 'Bracelets',
    categorySlug: 'bracelets',
    tagline: 'Structured, earthy, yours',
    description:
      'A wide cuff bracelet woven on a loom — a more traditional technique I returned to after years of off-loom work. The earth-tone palette (ochre, umber, cream, and a single accent line of deep teal) is inspired by Pueblo pottery patterns. The cuff is 1.5" wide and rigid enough to hold its shape, but the seed beads give it warmth.',
    materials: 'Miyuki Delica beads, loom-woven on nylon thread, brass cuff blank',
    dimensions: '1.5" wide, fits 6.5–7.5" wrist',
    colors: ['ochre', 'umber', 'cream', 'teal'],
    placeholderClass: 'placeholder-earth',
    inStock: true,
    featured: false,
    isNew: true,
  },
  {
    id: '7',
    slug: 'sacred-geometry-earrings',
    name: 'Sacred Geometry Earrings',
    price: 55,
    category: 'Earrings',
    categorySlug: 'earrings',
    tagline: 'Pattern as meditation',
    description:
      'Drop earrings formed from interlocking triangles — a peyote-stitched geometric design I\'ve been refining for two years. The dark midnight blue and ivory contrast makes the pattern pop. They\'re lightweight despite looking substantial, and the sterling ear wires are comfortable for all-day wear.',
    materials: 'Miyuki Delica beads (peyote stitch), sterling silver ear wires',
    dimensions: '2.5" drop length',
    colors: ['midnight blue', 'ivory'],
    placeholderClass: 'placeholder-midnight',
    inStock: true,
    featured: true,
    isNew: false,
  },
  {
    id: '8',
    slug: 'wildflower-hair-pin-set',
    name: 'Wildflower Hair Pin Set',
    price: 42,
    category: 'Hair Pieces',
    categorySlug: 'hair-pieces',
    tagline: 'Set of three, made to mix',
    description:
      'A set of three bobby pins each topped with a small beaded wildflower. One daisy, one poppy, one lavender sprig — I make them in groups so you can wear all three or pull them apart for different looks. The pins are gold-toned and the beads are seed beads in soft, faded naturals. A nice gift, or a treat for yourself.',
    materials: 'Glass seed beads, gold-toned bobby pins',
    dimensions: '0.75"–1" flowers, set of 3',
    colors: ['white', 'rose', 'lavender'],
    placeholderClass: 'placeholder-wild',
    inStock: true,
    featured: false,
    isNew: true,
  },
  {
    id: '9',
    slug: 'storm-cloud-choker',
    name: 'Storm Cloud Choker',
    price: 68,
    category: 'Necklaces',
    categorySlug: 'necklaces',
    tagline: 'Before the rain comes',
    description:
      'A close-fitting choker in steel blue, slate, and silver. I made this one during a particularly stormy week in November — you can feel the mood in it. The seed beads are Miyuki, a Japanese brand I trust for consistency. The choker sits snugly against the collarbone and closes with a small silver lobster clasp.',
    materials: 'Miyuki seed beads, sterling silver lobster clasp and chain extender',
    dimensions: '14–16" adjustable',
    colors: ['steel blue', 'slate', 'silver'],
    placeholderClass: 'placeholder-storm',
    inStock: true,
    featured: false,
    isNew: false,
  },
  {
    id: '10',
    slug: 'harvest-moon-pendant',
    name: 'Harvest Moon Pendant',
    price: 95,
    category: 'Necklaces',
    categorySlug: 'necklaces',
    tagline: 'Round and warm as October',
    description:
      'A large circular beaded pendant in golden amber and harvest orange. I built this pendant over a wooden form and it has a satisfying weight to it — you\'ll feel it when you wear it. The chain is 20" brass and the pendant hangs at the sternum. A real statement piece that works with a plain white shirt or layered over other necklaces.',
    materials: 'Glass seed beads, wooden form, 20" brass chain',
    dimensions: '2" diameter pendant, 20" chain',
    colors: ['amber', 'orange', 'gold'],
    placeholderClass: 'placeholder-harvest',
    inStock: true,
    featured: true,
    isNew: false,
  },
  {
    id: '11',
    slug: 'desert-rose-ring',
    name: 'Desert Rose Ring',
    price: 48,
    category: 'Rings',
    categorySlug: 'rings',
    tagline: 'Blooms in dry places',
    description:
      'A beaded ring in the shape of a desert rose — that mineral formation that looks like a flower made of stone. The dusty coral and cream palette feels both natural and romantic. Peyote stitch with size 11/0 seed beads. Adjustable band fits sizes 5–9.',
    materials: 'Miyuki Delica beads, brass adjustable ring band',
    dimensions: 'Adjustable, fits sizes 5–9',
    colors: ['dusty coral', 'cream', 'blush'],
    placeholderClass: 'placeholder-desert',
    inStock: false,
    featured: false,
    isNew: false,
  },
  {
    id: '12',
    slug: 'mountain-spirit-wall-art',
    name: 'Mountain Spirit Wall Art',
    price: 185,
    category: 'Wall Art',
    categorySlug: 'wall-art',
    tagline: 'For the walls you love',
    description:
      'My largest and most time-intensive piece — a beaded wall hanging that took six weeks to complete. The design is an abstracted mountain landscape in charcoal, slate, and sky. It\'s mounted on a birch driftwood branch with natural linen cord for hanging. This is a one-of-a-kind piece; I won\'t make another exactly like it. Measures 12" wide by 18" tall.',
    materials: 'Miyuki seed beads, birch driftwood, natural linen cord',
    dimensions: '12" wide × 18" tall',
    colors: ['charcoal', 'slate', 'sky', 'cream'],
    placeholderClass: 'placeholder-mountain',
    inStock: true,
    featured: true,
    isNew: false,
  },
]

export const categories = [
  { name: 'Necklaces', slug: 'necklaces', placeholderClass: 'placeholder-turquoise' },
  { name: 'Bracelets', slug: 'bracelets', placeholderClass: 'placeholder-earth' },
  { name: 'Earrings',  slug: 'earrings',  placeholderClass: 'placeholder-mesa' },
  { name: 'Rings',     slug: 'rings',     placeholderClass: 'placeholder-prairie' },
  { name: 'Hair Pieces', slug: 'hair-pieces', placeholderClass: 'placeholder-wild' },
  { name: 'Wall Art',  slug: 'wall-art',  placeholderClass: 'placeholder-mountain' },
]

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug) || null
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured)
}

export function getProductsByCategory(categorySlug) {
  return products.filter((p) => p.categorySlug === categorySlug)
}
